### PR TITLE
added function to get doc clusters from index and hashed docs

### PR DESCRIPTION
**Pull request by coderpendent**
Added a function to identify clusters of similar documents.  This will produce a dictionary of sets where the sets contain the documents that are matched by get_near_dups().  This function is useful when you want to group documents by similarity.

### CODE REVIEW

**Comment by 1e0ng** [comment]
Hi, thanks for your proposal.

One question is what if there are some conflicts?
For example, doc A and doc B are similar (by checking `get_near_dups`), and doc B and doc C are also similar, but doc A and doc C are *not* similar. In this case, how should we group them?

**Comment by coderpendent** [comment]
I was thinking of relying on the transitive property, but it would also be nice to give users the option of choosing a different method, like a Jaccard threshold or something else.  However, as I thought about how that might be implemented I began to doubt it would make sense to include in this library, because it would start to stray from being just a SimHash implementation.  What do you think?

**Comment by 1e0ng** [comment]
Yes, @coderpendent I agree on that, it depends on how users use them, and it's independent of SimHash implementation. At the same time, kindly remind that the hash value is multi-dimensional rather than one, so there could be some cases where the transitive property does not work.

**Comment by coderpendent** [comment]
Closing PR - see conversation

**Pull request closed without merging**
